@startuml
'https://plantuml.com/sequence-diagram

title API - Use Case 4.1.1 - Teilnehmer - Verwalten

note across #green: Finish

==Teilnehmer abfragen/löschen==
"Client\n(Admin)" -> "[GET|DELETE]\n /admin/user/{username}"
"Client\n(Admin)" <- "[GET|DELETE]\n /admin/user/{username}": User

==Teilnehmer hinzufügen/bearbeiten==
"Client\n(Admin)" -> "[POST|PUT]\n /admin/user/{username}": CreateUser
"Client\n(Admin)" <- "[POST|PUT]\n /admin/user/{username}": User
@enduml
@startuml
title Use Case 4.1.1.1 Abrechnungstoken verwalten
note across #yellow: Not Started

==QR-Code erstellen==
"Client\n(Admin)" -> "[POST]\n /admin/user/{username}/qr":
"Client\n(Admin)" <- "[POST]\n /admin/user/{username}/qr": QR-Code-Status

==QR-Code deaktivieren==
"Client\n(Admin)" -> "[DELETE]\n /admin/user/{username}/qr":
"Client\n(Admin)" <- "[DELETE]\n /admin/user/{username}/qr": QR-Code-Status

==QR-Code zum Drucken abfragen==
"Client\n(Admin)" -> "[GET]\n /admin/user/{username}/qr":
"Client\n(Admin)" <- "[GET]\n /admin/user/{username}/qr": QR-Code
@enduml
@startuml
title Use Case 4.2 Produkte Verwalten
note across #green: Finish

==Produkt abfragen/löschen==
"Client\n(Admin)" -> "[GET|DELETE]\n /admin/product/{id}"
"Client\n(Admin)" <- "[GET|DELETE]\n /admin/product/{id}": Product

==Produkt bearbeiten==
"Client\n(Admin)" -> "[PUT]\n /admin/product/{id}": Product
"Client\n(Admin)" <- "[PUT]\n /admin/product/{id}": Product

==Produkt hinzufügen==
"Client\n(Admin)" -> "[POST]\n /admin/product/": Product
"Client\n(Admin)" <- "[POST]\n /admin/product/": Product

@enduml