### Use Case 1 - User Login
POST localhost:8080/token
Content-Type: application/json

{
  "username": "barkeeper",
  "password": "barkeeper"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
client.global.set("auth_token_bar", "" + response.body);
%}


### Use Case 1.1 - Bestell historie ansehen
GET localhost:8080/bar/order/


### Use Case 1.2 - Kostenlimmit festlegen

### Use Case 1.3 - Getränke bestellen

### Use Case 1.3.1 - Getränke bestellen via Tresen

### Produkte abfragen
GET localhost:8080/bar/product/

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Nutzer abfragen
GET localhost:8080/bar/user/

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Bestellung abschicken
POST localhost:8080/bar/order/
Content-Type: application/json

{
  "id": null,
  "purchaser": "Ute Pillow",
  "positions": {
    "11": 20,
    "12": 10
  }
}

### Bestellung abschicken mit Fehler
POST localhost:8080/bar/order/
Content-Type: application/json

{
  "id": null,
  "purchaser": "Ute Pillow",
  "positions": {
    "0": 20,
    "12": 10
  }
}

### Bestellung abschicken mit Fehler
POST localhost:8080/bar/order/
Content-Type: application/json

{
  "id": null,
  "purchaser": "Ute PillX",
  "positions": {
    "0": 20,
    "12": 10
  }
}

### Bestellung stornieren
DELETE localhost:8080/bar/order/18/